# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170227_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lang',
            field=models.CharField(default='fr', max_length=15),
        ),
    ]
