security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            #anonymous: true
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            form_login:
                login_path: app_login
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: login$, roles: PUBLIC_ACCESS }
        - { path: /anon/language/*, roles: PUBLIC_ACCESS }
        - { path: ^/webhook, roles: PUBLIC_ACCESS }
        - { path: ^/creer-compte, roles: PUBLIC_ACCESS }
        - { path: /vacances-en-eusko, roles: PUBLIC_ACCESS }
        - { path: /ouverture-compte, roles: PUBLIC_ACCESS }
        - { path: /adhesion, roles: PUBLIC_ACCESS }
        - { path: /poursuiteInscription, roles: PUBLIC_ACCESS }
        - { path: /signature-mandat-cotisation, roles: PUBLIC_ACCESS }
        - { path: /ajax/zipcode, roles: PUBLIC_ACCESS }
        - { path: /vacances-en-eusko/coordonnees, roles: PUBLIC_ACCESS }
        - { path: /premiere/connexion, roles: PUBLIC_ACCESS }
        - { path: /fermeture/compte, roles: PUBLIC_ACCESS }
        - { path: /activer-compte, roles: PUBLIC_ACCESS }
        - { path: /valide-premiere-connexion, roles: PUBLIC_ACCESS }
        - { path: /passe-perdu, roles: PUBLIC_ACCESS }
        - { path: /valide-passe-perdu, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }

        # - { path: ^/profile, roles: ROLE_USER }
