twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@SonataCore/Form/datepicker.html.twig'
    globals:
        yousign_url: '%env(YOUSIGN_URL)%'
