twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    form_themes:
        - '@SonataForm/Form/datepicker.html.twig'
    globals:
        yousign_url: '%env(YOUSIGN_URL)%'
        yousign_mode: '%env(YOUSIGN_MODE)%'

when@test:
    twig:
        strict_variables: true