legacy_login:
    path: /login
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: '/fr/login'
        permanent: true
legacy_vee:
    path: /vacances-en-eusko
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: '/fr/vacances-en-eusko'
        permanent: true
